### PR TITLE
OxyPlot Xamarin.Forms UWP Release Workaraound

### PR DESCRIPTION
**Pull request by dimitrijevic**
These changes make the plot visible in Release mode.

### CODE REVIEW

**Comment by dimitrijevic** [comment]
What failed bitrise? I've got no access, but AppVeyor seems to work.

**Comment by dimitrijevic** [comment]
Can you give access to bitrise.io so I can see what failed?

**Comment by objorke** [comment]
it fails on an iPhone provisioning / certificate installation step...
@dimitrijevic, I added you as member on the bitrise project!

```
+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+---+---------------------------------------------------------------+----------+
|   | title                                                         | time (s) |
+---+---------------------------------------------------------------+----------+
| ✓ | activate-ssh-key@3.1.1                                        | 2.89 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | git-clone@3.4.0                                               | 6.49 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 3.4.0 -> 3.4.1                                             |
+---+---------------------------------------------------------------+----------+
| ✓ | Do anything with Script step                                  | 3.43 sec |
+---+---------------------------------------------------------------+----------+
| x | certificate-and-profile-installer@1.7.0 (exit code: 1)        | 5.51 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 1.7.0 -> 1.8.2                                             |
| Issue tracker: .../bitrise-io/steps-certificate-and-profile-installer/issues |
| Source: ...s://github.com/bitrise-io/steps-certificate-and-profile-installer |
+---+---------------------------------------------------------------+----------+
| ✓ | xamarin-user-management@1.0.3                                 | 3.05 sec |
+---+---------------------------------------------------------------+----------+
| - | nuget-restore@0.9.3                                           | 1.12 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 0.9.3 -> 1.0.3                                             |
+---+---------------------------------------------------------------+----------+
| - | xamarin-builder@1.4.1                                         | 1.14 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 1.4.1 -> 1.4.2                                             |
+---+---------------------------------------------------------------+----------+
| ✓ | deploy-to-bitrise-io@1.2.5                                    | 5.51 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 1.2.5 -> 1.2.9                                             |
+---+---------------------------------------------------------------+----------+
| Total runtime: 29 sec                                                        |
+------------------------------------------------------------------------------+
```

**Comment by objorke** [comment]
created #54

**Comment by dimitrijevic** [comment]
TBH, I hadn't heard of bitrise.io, prior to this...but I'll look soon...until then, I'm closing my issue referencing https://github.com/oxyplot/oxyplot-xamarin/issues/53, as I'm sure that's not the problem.
Have you got a provisioning certificate for the iOS app store? It costs 99USD for apps per year to publish on iOS, is it affordable for an open source with no donations to purchase it, as I didn't see any on oxyplot.org website?
I have access to a faculty ceritificate, but you can't publish to store or flight test with it, only use it on 200 pre-defined UDID devices.

**Comment by objorke** [comment]
I see the Xamarin subscription expired Feb 11.
The Apple developer subscription should be valid until June.
I will try to renew the Xamarin subscription.

**Comment by objorke** [comment]
bitrise.io was used since it supports builds for Xamarin.Mac
The last successful build was 2016.10.07 https://www.bitrise.io/build/bc0278b0f179b0fd
@dimitrijevic I changed your bitrise role to admin, feel free to try changing the settings!

**Pull request merged**
