### PR TITLE
Refactoring and cleanup for Windows/UWP

### PR DESCRIPTION
**Pull request by janusw**
This PR cleans up the Windows/UWP part of OxyPlot.Xamarin, which is special in that it depends on the package Oxyplot.Windows, which lives outside of this repo.

Therefore I first copied the code from the oxyplot-uwp repo into oxyplot-xamarin, in analogy to the other platforms. Since the OxyPlot.Windows project did not actually build, I made some changes to fix that. Then I consolidated the package versions across the sln, updated the nuspec and did some further cleanup.

@objorke @VisualMelon I hope this restructuring is ok with you.

### CODE REVIEW

**Comment by VisualMelon** [comment]
Is there a reason that the Windows/UWP stuff can't stay in its own repo? It's fine to have an inter-repo dependence so long as it is simple and documented or managed nicely with git sub-module. I may be missing the point entirely.

**Comment by janusw** [comment]
> Is there a reason that the Windows/UWP stuff can't stay in its own repo?

Well, it certainly could, but honestly that does not make much sense to me.

First of all, there does not seem to be much general interest in the UPW port on its own. The repo is a one-commit drop from the main oxyplot repo AFAICS, which has not been touched ever since and does not build at all.

I don't personally have much incentive for maintaining yet another package, with all its interdependencies etc. Updating the Xamarin package is much easier with everything in one place, and that's also the way it is done for the other platforms (Android, iOS, Mac). I have abandoned the Xamarin.Android, Xamarin.iOS and Xamarin.Mac packages and only plan to further maintain the Xamarin.Forms package, which IMHO is the future and can be developed into a MAUI package at some point. The platform-specific Xamarin-variants are not very relevant any more, I think (but in principle they can still be used via the Xamarin.Forms package, which contains everything now).

I would like to treat Windows/UWP in the same way as the other platforms, thus deprecating OxyPlot.Windows (which is misnamed anyway; should rather be called OxyPlot.UWP) and include it directly in OxyPlot.Xamarin.Forms. This reduces the maintenance overhead, makes it simpler to consistenly update everything to new package versions etc (and, as for the other platforms, it is still possible to use the UWP parts for a pure Xamarin.UWP app).

In any case I think UWP will be irrelevant and outdated pretty soon, and will be replaced by WinUI 3 (which is also used for MAUI). I would like to move all of this towards MAUI as fast as possible, and dragging along too much historical ballast will only slow down this process and make it unnecessarily complicated.

I hope I explained my reasoning well and it does make some sense to you ;)

**Comment by VisualMelon** [comment]
If it makes it easy for you, then I'm happy.

**Comment by janusw** [comment]
> If it makes it easy for you, then I'm happy.

Ok, then. Thanks for your understanding! 😊

I'm going to merge this PR and add a deprecation notice to oxyplot-uwp, which links to oxyplot-xamarin.

Btw, we can of course easily publish a pure UWP package again in the future, if we decide that it's necessary. But I really think there is zero value in keeping it in a separate repo (in particular in a one-commit repo without any historical context).

**Pull request merged**
