### PR TITLE
Update to Xamarin.Forms 2.2

### PR DESCRIPTION
**Pull request by scastria**
Updated all project nuget references in Xamarin.Forms solution to allow building a new OxyPlot.Xamarin.Forms based nuget packages against Xamarin.Forms 2.2

### CODE REVIEW

**Comment by objorke** [comment]
Thanks! This looks good!
Note that we are now pushing all pre-release packages to myget
https://github.com/oxyplot/oxyplot-xamarin/blob/develop/appveyor.yml#L36
Will push to NuGet when we reach a stable release!

**Comment by scastria** [comment]
Thanks, I am having trouble accessing myget.  I get "No packages found." when I run:

nuget list -Source https://www.myget.org/F/oxyplot

**Comment by scastria** [comment]
Nevermind, I forgot to check the "show pre-release" button.

**Comment by prajithmp** [comment]
when will i receive a stable version for xamarin forms 2.3

**Comment by objorke** [comment]
@prajithmp See #13

**Pull request merged**
